### ISSUE TITLE
pyerfa install fails with pip 22.2 and python 3.10.5

### ISSUE THREAD

**Issue by tbridel** [liberfa/pyerfa#86]
Hi everyone !

I am building an app that requires pyerfa (_via_ poliastro actually), and it turns out that with python 3.10.5 and pip 22.2, the install with pip fails because of a metadata inconsistency.

```
Collecting pyerfa
  Downloading pyerfa-2.0.0.1.tar.gz (808 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 808.5/808.5 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/78/fd/0148f0e54f0c6f48a141409df65d74a5f1dae2e139f23d50a43c58c16098/pyerfa-2.0.0.1.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.7): Requested pyerfa from https://files.pythonhosted.org/packages/78/fd/0148f0e54f0c6f48a141409df65d74a5f1dae2e139f23d50a43c58c16098/pyerfa-2.0.0.1.tar.gz has inconsistent version: filename has '2.0.0.1', but metadata has '0.0.0'
  Downloading pyerfa-2.0.0.tar.gz (808 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 808.3/808.3 kB 12.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/03/71/47b58cbbf8350209f0be27177d9ecc15df8956bbf00af74cb9cd2abc5df1/pyerfa-2.0.0.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.7): Requested pyerfa from https://files.pythonhosted.org/packages/03/71/47b58cbbf8350209f0be27177d9ecc15df8956bbf00af74cb9cd2abc5df1/pyerfa-2.0.0.tar.gz has inconsistent version: filename has '2.0.0', but metadata has '0.0.0'
  Downloading pyerfa-1.7.3.tar.gz (768 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 768.3/768.3 kB 9.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/2f/87/a3a31eddf7952c2741e2871aed365aca21423b546a51fd0375306f66e460/pyerfa-1.7.3.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.6): Requested pyerfa from https://files.pythonhosted.org/packages/2f/87/a3a31eddf7952c2741e2871aed365aca21423b546a51fd0375306f66e460/pyerfa-1.7.3.tar.gz has inconsistent version: filename has '1.7.3', but metadata has '0.0.0'
  Downloading pyerfa-1.7.2.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/e3/af/ae39c2b1f652895238888f186579b7eedb9f55fdbde78ad75f34597059bc/pyerfa-1.7.2.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.6): Requested pyerfa from https://files.pythonhosted.org/packages/e3/af/ae39c2b1f652895238888f186579b7eedb9f55fdbde78ad75f34597059bc/pyerfa-1.7.2.tar.gz has inconsistent version: filename has '1.7.2', but metadata has '0.0.0'
  Downloading pyerfa-1.7.1.1.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 13.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/3b/37/0ff81021f6405e4f6f627bb4aed32d22569fe016376dccee14e5eca947d1/pyerfa-1.7.1.1.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.6): Requested pyerfa from https://files.pythonhosted.org/packages/3b/37/0ff81021f6405e4f6f627bb4aed32d22569fe016376dccee14e5eca947d1/pyerfa-1.7.1.1.tar.gz has inconsistent version: filename has '1.7.1.1', but metadata has '0.0.0'
  Downloading pyerfa-1.7.1.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 15.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/d6/58/f18be3ace5066283f8e8cb7385301aebb0adacda70a09235c4f5675bd673/pyerfa-1.7.1.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.6): Requested pyerfa from https://files.pythonhosted.org/packages/d6/58/f18be3ace5066283f8e8cb7385301aebb0adacda70a09235c4f5675bd673/pyerfa-1.7.1.tar.gz has inconsistent version: filename has '1.7.1', but metadata has '0.0.0'
  Downloading pyerfa-1.7.0.tar.gz (490 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.7/490.7 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/86/5d/f4cc5804744f7ab14b54059ebd44969e4f6af9eb6909f56d112bf9f0730b/pyerfa-1.7.0.tar.gz (from https://pypi.org/simple/pyerfa/) (requires-python:>=3.6): Requested pyerfa from https://files.pythonhosted.org/packages/86/5d/f4cc5804744f7ab14b54059ebd44969e4f6af9eb6909f56d112bf9f0730b/pyerfa-1.7.0.tar.gz has inconsistent version: filename has '1.7.0', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement pyerfa (from versions: 1.7.0, 1.7.1, 1.7.1.1, 1.7.2, 1.7.3, 2.0.0, 2.0.0.1)
ERROR: No matching distribution found for pyerfa
```

I have tried downgrading pip but to no avail.
Anyone knows what is happening ?

Thank you so much for pyerfa and your support !!

**Comment by tbridel** [comment]
@avalentino

**Comment by avalentino** [comment]
Dear @tbridel,
sorry, I'm not able to reproduce:

```sh
$ conda create -n pyerfa -c conda-forge  python==3.10.5 pip==22.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/antonio/anaconda3/envs/pyerfa

  added / updated specs:
    - pip==22.2
    - python==3.10.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libffi-3.4.2               |       h7f98852_5          57 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          57 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ca-certificates    conda-forge/linux-64::ca-certificates-2022.6.15-ha878542_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_2
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1
  openssl            conda-forge/linux-64::openssl-3.0.5-h166bdaf_0
  pip                conda-forge/noarch::pip-22.2-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.10.5-ha86cf86_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  readline           conda-forge/linux-64::readline-8.1.2-h0f457ee_0
  setuptools         conda-forge/linux-64::setuptools-63.2.0-py310hff52083_0
  sqlite             conda-forge/linux-64::sqlite-3.39.2-h4ff8645_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.12-h166bdaf_2


Proceed ([y]/n)? 


Downloading and Extracting Packages
libffi-3.4.2         | 57 KB     | ########################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pyerfa
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate pyerfa
(pyerfa) $ pip install pyerfa
Collecting pyerfa
  Downloading pyerfa-2.0.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (743 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 743.2/743.2 kB 6.0 MB/s eta 0:00:00
Collecting numpy>=1.17
  Downloading numpy-1.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 7.8 MB/s eta 0:00:00
Installing collected packages: numpy, pyerfa
Successfully installed numpy-1.23.1 pyerfa-2.0.0.1
```

**Comment by tbridel** [comment]
Hello @avalentino !

Thank you for trying. It means that somehow pip is broken on Mac OS X then 🤔 
Can you share what OS you are on ?

**Comment by avalentino** [comment]
It is Ubuntu 22.04 x86_64

**Comment by tbridel** [comment]
Hmm ok, thanks ! I'll try to investigate why pip is broken on Mac OS X ... 
If you have any idea/pointer, i'd be grateful ! :)

**Comment by avalentino** [comment]
OK, just repeated the same test on OSX 12.4 (intel) and, also in this case, it works.
Maybe you have some additional package already installed that creates conflicts.

**Comment by tbridel** [comment]
Ah ! Really ? Hmm ok, i'll try from a clean install of python3.10 then ! I'll keep you in the loop, thank you for trying :)

**Comment by avalentino** [comment]
If you have conda you could try the very same procedure described above.
It does not take too long
At the end you can throw away the environment if you no longer need it.

**Comment by tbridel** [comment]
I don't have anaconda right now so I removed all the local packages and uninstalled python3.10 to restart from a fresh 3.10.5 install with pip 22.2 like you. 
Same problem on this fresh install.

I could only install pyerfa with `/opt/homebrew/opt/python@3.10/bin/python3 -m pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver pyerfa` after installing manually `numpy`. 

Unfortunately this is not a solution since I have to install an entire `requirements.txt` file and the legacy resolver won't do the job.

**Comment by defjaf** [comment]
I am getting similar issues on Apple silicon. Complete failure with the standard (new) resolver. When I try the legacy resolver, I get the messages below. Note the strange version number. But at least now I can import (e.g.) astropy and healpy. (Not rigorously tested, though.)

```
$ /opt/homebrew/opt/python@3.10/bin/python3 -m pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver pyerfa 
Collecting pyerfa
  Downloading pyerfa-2.0.0.1.tar.gz (808 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 808.5/808.5 kB 90.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied, skipping upgrade: numpy>=1.17 in /opt/homebrew/lib/python3.10/site-packages (from pyerfa) (1.23.1)
Building wheels for collected packages: pyerfa
  Building wheel for pyerfa (pyproject.toml) ... done
  Created wheel for pyerfa: filename=pyerfa-0.0.0-cp310-cp310-macosx_12_0_arm64.whl size=330893 sha256=065d0f4fc5b822aeddcf9c60b5e02a26f9657ea5ac3af90e6081a310c5cb0ea0
  Stored in directory: /private/var/folders/s3/h4b8_8qn4sv46q8_h29yx4cr0000gn/T/pip-ephem-wheel-cache-0js2hlqw/wheels/6c/e5/7f/b5af8c19e0c997690ebe099bcb661c67fd4bb1a6a017d3a9f8
Successfully built pyerfa
Installing collected packages: pyerfa
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
astropy 5.1 requires pyerfa>=2.0, but you'll have pyerfa 0.0.0 which is incompatible.
Successfully installed pyerfa-0.0.0

```

**Comment by avalentino** [comment]
Yes, there seems to be something strange in the setup process.
Could you please confirm that the `erfa.__version__` contains the correct version number?

**Comment by defjaf** [comment]
Yes:

```
$ python3.10
Python 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import erfa
>>> print(erfa.__version__)
2.0.0.1
>>>  
```

**Comment by brittjeter** [comment]
Hi folks, I was running into a similar problem, running on a fresh install of python 3.10.6 and pip 22.2.2, installed via Homebrew on Apple silicon.  I was able to fix the issue by installing setuptools_scm with `pip3 install setuptools_scm`.  After this, I was able to successfully install pyERFA 2.0.0.1, and subsequently astropy 5.1.

**Comment by avalentino** [comment]
`setuptools_scm` is listed in the `pyproject.toml` so I would expect that it is installed when `pip` starts building `pyerfa`.
Any thought?

**Comment by defjaf** [comment]
I have found the same experience as @brittjeter. `setuptools_scm` was *not* automatically installed as a dependency, but when I did it by hand, everything worked fine, including with correct version numbers:

```
~$ pip3 install setuptools_scm
Collecting setuptools_scm
  Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
Requirement already satisfied: typing-extensions in /opt/homebrew/lib/python3.10/site-packages (from setuptools_scm) (4.3.0)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.10/site-packages (from setuptools_scm) (21.3)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.10/site-packages (from setuptools_scm) (65.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/homebrew/lib/python3.10/site-packages (from packaging>=20.0->setuptools_scm) (3.0.9)
Installing collected packages: tomli, setuptools_scm
Successfully installed setuptools_scm-7.0.5 tomli-2.0.1

~$ pip3 uninstall pyerfa
Found existing installation: pyerfa 0.0.0
Uninstalling pyerfa-0.0.0:
  Would remove:
    /opt/homebrew/lib/python3.10/site-packages/erfa/*
    /opt/homebrew/lib/python3.10/site-packages/pyerfa-0.0.0.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled pyerfa-0.0.0

~$ pip3 install pyerfa
Collecting pyerfa
  Using cached pyerfa-2.0.0.1.tar.gz (808 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17 in /opt/homebrew/lib/python3.10/site-packages (from pyerfa) (1.23.2)
Building wheels for collected packages: pyerfa
  Building wheel for pyerfa (pyproject.toml) ... done
  Created wheel for pyerfa: filename=pyerfa-2.0.0.1-cp310-cp310-macosx_12_0_arm64.whl size=331253 sha256=12567e77ccbbda8485bc19633a270a7ee195b512c4ddd5e2d05d1cc1d2083c05
  Stored in directory: /Users/jaffe/Library/Caches/pip/wheels/6c/e5/7f/b5af8c19e0c997690ebe099bcb661c67fd4bb1a6a017d3a9f8
Successfully built pyerfa
Installing collected packages: pyerfa
Successfully installed pyerfa-2.0.0.1
```

**Comment by defjaf** [comment]
There is some [evidence](https://stackoverflow.com/questions/58521386/should-setuptools-be-in-the-setup-requires-entry-of-setup-cfg-files) (see also [pep 518](https://peps.python.org/pep-0518/#rationale)) that `setup_requires`, which is where you have `setuptools_scm`, doesn't quite work as intended, perhaps in just this situation.

**Comment by avalentino** [comment]
What are your pip and setuptools versions?

**Comment by defjaf** [comment]
All the latest, I think:

```
~$ pip3 --version
pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)

~$ python3
Python 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> print(setuptools.__version__)
65.0.0
```

**Comment by avalentino** [comment]
Using the `--use-pep517` pip option does help?

**Comment by avalentino** [comment]
It seems to be an OS specific issue.
On GNU/Linux the following command shows that `setuptoold_scm` is properly installed before building `pyerfa` form spurces:
```
pip install --no-binary pyerfa --verbose --log install.log pyerfa
```

**Comment by defjaf** [comment]
> It seems to be an OS specific issue.

Well, perhaps. But I hope it's ok to point out that I've got ~250 packages installed and this is the only one with which I've encountered this issue. (But I appreciate that this corner of install-parameter space may not be very high priority...)

**Comment by avalentino** [comment]
Sure. I would be very happy to implement a fix or a workaround, bur since I'm not able to reproduce the issue locally, it is very hard for me to figure out what is going wrong and to fix it.
A PR in this case would be very appreciated.

**Comment by avalentino** [comment]
@mhvk, @astrofrog are you able to reproduce this issue?

**Comment by mhvk** [comment]
I'm on linux, so cannot really test, but one thing I noticed is that `setup.cfg` still has an `install_requires` which only lists numpy. Might it help either removing that line or adding `setuptools_scm` to it? Apologies if this is known not to be relevant; I've never really understood how python does installation.

**Comment by avalentino** [comment]
Well, `setuptools_scm` is not really needed once the package is installed AFAIK, so IMHO it is correct to not list it in `install_requires`.
`setuptools_scm` is listed in `setup_requires` because it is needed to run the setup script, even if, in principle, this is redundant with what specified in `pyproject.toml`.
Probably we could drop `setup_requires` but AFAI it should not hurt.

Regarding the possibility to remove `numpy` from `install_requires` I don't think it is a good idea.
`install_requires` is what we currently use to declare (runtime) dependencies (see also https://setuptools.pypa.io/en/latest/userguide/quickstart.html#dependency-management).

**Comment by avalentino** [comment]
@defjaf, @tbridel in #87 we verified that in some cases installation issues could be related to brew.
Do you have a chance to replicate your tests using a different version of Python (e.g. form conda or pyenv)?

**Comment by mpeel** [comment]
Hi, I just came across this same issue, on a fresh install of python using homebrew. Installing setuptools_scm first solved it.

Mac OS 12.6, Apple silicon (M1 Pro), Homebrew 3.6.6, pip 22.3, python 3.10.8.

**Comment by jdavies-st** [comment]
Installing an an M1 MacOS 12.6 and conda version of python 3.10.6 and pip 22.2.2 works fine.  So perhaps this is a `brew` problem with Mac M1 only.

```
$ conda create -n pyerfa python -y
Collecting package metadata (current_repodata.json): done
Solving environment: done


## Package Plan ##

  environment location: /Users/jdavies/opt/miniconda3/envs/pyerfa

  added / updated specs:
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.07.19 |       hecd8cb5_0         124 KB
    certifi-2022.9.24          |  py310hecd8cb5_0         155 KB
    libcxx-14.0.6              |       h9765a3e_0         968 KB
    ncurses-6.3                |       hca72f7f_3         857 KB
    openssl-1.1.1q             |       hca72f7f_0         2.2 MB
    pip-22.2.2                 |  py310hecd8cb5_0         2.4 MB
    python-3.10.6              |       hdfd78df_0        10.7 MB
    setuptools-63.4.1          |  py310hecd8cb5_0         1.1 MB
    sqlite-3.39.3              |       h707629a_0         1.2 MB
    tk-8.6.12                  |       h5d9f67b_0         3.1 MB
    tzdata-2022e               |       h04d1e81_0         107 KB
    xz-5.2.6                   |       hca72f7f_0         243 KB
    zlib-1.2.12                |       h4dc903c_3          95 KB
    ------------------------------------------------------------
                                           Total:        23.1 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  ca-certificates    pkgs/main/osx-64::ca-certificates-2022.07.19-hecd8cb5_0
  certifi            pkgs/main/osx-64::certifi-2022.9.24-py310hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-14.0.6-h9765a3e_0
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.3-hca72f7f_3
  openssl            pkgs/main/osx-64::openssl-1.1.1q-hca72f7f_0
  pip                pkgs/main/osx-64::pip-22.2.2-py310hecd8cb5_0
  python             pkgs/main/osx-64::python-3.10.6-hdfd78df_0
  readline           pkgs/main/osx-64::readline-8.1.2-hca72f7f_1
  setuptools         pkgs/main/osx-64::setuptools-63.4.1-py310hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.39.3-h707629a_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  tzdata             pkgs/main/noarch::tzdata-2022e-h04d1e81_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.6-hca72f7f_0
  zlib               pkgs/main/osx-64::zlib-1.2.12-h4dc903c_3


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pyerfa
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate pyerfa
(pyerfa) $ pip install "pyerfa>=2"
Collecting pyerfa>=2
  Downloading pyerfa-2.0.0.1-cp310-cp310-macosx_10_9_x86_64.whl (340 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.4/340.4 kB 6.2 MB/s eta 0:00:00
Collecting numpy>=1.17
  Downloading numpy-1.23.4-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 14.1 MB/s eta 0:00:00
Installing collected packages: numpy, pyerfa
Successfully installed numpy-1.23.4 pyerfa-2.0.0.1
```

**Comment by avalentino** [comment]
Thanks for reporting @mpeel and @jdavies-st.
For me it is clear that the issue is linked to brew and maybe it has been already fixed meanwhile.
I'm closing the issue.
Please feel free to re-open if there are new info indicating an issue in pyerfa.

**Comment by mpeel** [comment]
Hi, just to note that I'm using the latest brew version, so I doubt this has been fixed meanwhile unless it's in a pre-release.

**Comment by dhomeier** [comment]
Just confirming that it is still throwing the same error with pip 22.3.1 and the Python 3.11 package version.

**Comment by nega0** [comment]
Piling on to the _metoos_... seems to work as expected in a python virtual environment (`python -m venv` specifically). It seems to be just Homebrew's `python` _outside_ of a virtual environment where it falls down.
